### ISSUE TITLE
Issue about Robust classifier: AT-A, DD-A, RC-A and Low-rank approximation LRA-A code

### ISSUE THREAD

**Issue by icmpnorequest** [jjy1994/AttriGuard#1]
Hi Jinyuan, 
I've read your paper AttriGuard and wanted to do the experiment. In the sourcecode, I didn't find codes about robust classifier as the paper post in section 5.1.2 attribute inference attack. Could you please upload that related codes or tell me something coding ideas about that models?
Thanks in advance!

**Comment by jinyuan-jia** [comment]
Hi icmpnorequest,
   In terms of robust classifier, you can refer to the paper cited by our paper, many of them should have publish available implementation. For example, adversarial training and defensive distillation (you can search it online in which there is public available implementation). The RC should be very easy to implement in which the information in a hypercube centered at the input is aggregated to predict its label.  For LRA, we use non-negative matrix factorization in which there are many public available implementations (e.g, sk-learn). Hope this helps and sorry for the late reply.

**Comment by icmpnorequest** [comment]
> Hi icmpnorequest,
> In terms of robust classifier, you can refer to the paper cited by our paper, many of them should have publish available implementation. For example, adversarial training and defensive distillation (you can search it online in which there is public available implementation). The RC should be very easy to implement in which the information in a hypercube centered at the input is aggregated to predict its label. For LRA, we use non-negative matrix factorization in which there are many public available implementations (e.g, sk-learn). Hope this helps and sorry for the late reply.

Thank you so much for your guidance and patience. I will implement the experiment according to your guidance. Thanks again!
